upd: update env in agent
MakeItBright/go-metrics-devops pull request #5
Opened 2023-04-14 23:08 UTC by MakeItBright

2023-04-15 19:34 UTC, mshogin requested changes
Отлично, что приложение проходит все тесты. Однако, для того чтобы код был "устойчивым и легко поддерживаемым", необходимо пересмотреть кодовую базу. Я предлагаю несколько вариантов для улучшения.

2023-04-15 19:34 UTC, mshogin commented on cmd/agent/main.go
> +	}
agent/main.go
предлагаю привести main.go к виду
```
<PSEUDOCODE BEGIN>

	cfg := config.NewAgentConfig()
	if err := agent.Start(cfg); err != nil {
		log.Fatal(err)
	}

<PSEUDOCODE END>
```

предлагаю перенести всю работу связанную с созданием конфига в internal/config/agent.go
долно получится так
```
<PSEUDOCODE BEGIN>

function NewAgentConfig() *AgentConfig {
	cfg := &AgentConfig{
		LogLevel: "debug",
	}

	if err := cfg.fillFromEnv(); err != nil {
		return nil, fmt.Errorf("cannot initialize config from ENV: %w", err)
	}

        if err := cfg.fillFromArgs(); err != nil {
		return nil, fmt.Errorf("cannot initialize config from args: %w", err)
	}

	return cfg, nil
}

<PSEUDOCODE END>
```

предлагаю првести internal/agent/agent.go к виду
```
<PSEUDOCODE BEGIN>

pollTicker := time.NewTicker(pollInterval) // pollInterval = a.GetPollInterval()
reportTicker := time.NewTicker(reportInterval) // similar to pollInterval

m := monitor.NewMonitor(storage.NewStorage(), sender.NewSender())

for {
	select {
	case <-pollTicker.C:
		m.CollectMetrics()
	case <-reportTicker.C:
                m.Dump()
	}
}

<PSEUDOCODE END>
```

для этого предлагаю создать internal/monitor/monitor.go
```
<PSEUDOCODE BEGIN>

struct monitor {
	storage storage.Storage
	sender sender.Sender
}

function NewMonitor(storage storage.Storage, sender sender.Sender) *monitor {
	return &Monitor{
		storage: storage,
		sender: sender,
	}
}

method CollectMetrics() {
        m.collectRuntimeMetrics()
        m.collectSystemMetrics()
}

method collectRuntimeMetrics() {
    // здесь логика сбора метрик и сохранения их в storage
    // get runtime metrics
    ...
    m.storage.AddGauge("BuckHashSys", 123.45)
}

method collectSystenMetrics() {
    // здесь логика сбора метрик и сохранения их в storage
    // get system metrics like random and counter
    ...
    m.storage.IncrementCounter("PollCounter", 1)
}

method Dump() {
	// здесь логика получения всех метрик и отправки метрик на сервер
}

<PSEUDOCODE END>
```

для этого потребуется в internal/storage/storage.go
написать код Storage
```
<PSEUDOCODE BEGIN>

interface Storage {
    AddGauge(name string, value float64)
    AddCounter(name string, value int64)
    GetGauge(name string) (float64, bool)
    GetCounter(name string) (int64, bool)
}

struct MemStorage {
    gaugeMap   map[string]float64
    counterMap map[string]int64
}

function NewMemStorage() *MemStorage {
    return &MemStorage{
        gaugeMap:   make(map[string]float64),
        counterMap: make(map[string]int64),
    }
}

// необходимо имплементировать следующие фунции
method AddGauge(name string, value float64)
method AddCounter(name string, value int64)
method GetGauge(name string) (float64, bool)
method GetCounter(name string) (int64, bool)
method GetAllMetrics() map[string]interface{}

<PSEUDOCODE END>
```
также в internal/sender/sender.go необходимо имплементировать Sender
```
<PSEUDOCODE BEGIN>

struct sender {
    url string
}

function NewSender(serverAddr string) *sender {
    return &sender{
        ServerAddr: serverAddr,
    }
}

method SendMetrics(metrics map[string]interface{}) error

<PSEUDOCODE END>
```

2023-04-15 19:34 UTC, mshogin commented on cmd/server/main.go
> +	}
server/main.go
предлагаю привести main.go к виду
```
    cfg := config.NewServerConfig()
    if err := server.Start(config); err != nil {
        log.Fatal(err)
    }
```

предлагаю перенести всю работу связанную с созданием конфига в internal/config/server.go также как и в случае с agent config

предлагаю првести internal/server/api.go к виду
```
<PSEUDOCODE BEGIN>

func Start(config *Config) error {
    store := storage.NewStorage()
    srv := newServer(store)
    return http.ListenAndServe(config.BindAddr, srv)
}

<PSEUDOCODE END>
```
соответственно мы удалим func init - эту фунуцию можно использовать когда все остальное не помогает. Обычно ее использование говорит о проблеме в дизайне приложения (хотя маскируется(продается) как advanced техника)
я также предлагаю избавится от inmem структуры и перейти на общий сторадж
там сейчас есть момент
```
method GetAllMetrics() map[string]interface{}
```
я предлагаю на текущий момент остаться с interface в map и избавится от него в следующей итерации ревью

далее в предлагаю поправить регистрацию роутов
```
<PSEUDOCODE BEGIN>

func (s *server) configureRouter() {
    s.router.Get("/health", s.handleHealth)
    s.router.Get("/", s.handleGetAllMetrics)
    s.router.Post("/update/{metricType}/{metricName}/{metricValue}", s.handlePostUpdateMetric)
    s.router.Get("/value/{metricType}/{metricName}", s.handleGetMetric)
}

<PSEUDOCODE END>
```
нам нет сейчас необходимости делать замыкание. Соответственно надо будет поправить декларацию хендлеров, чтобы они удовлетворяли HandleFunc interface
```
<PSEUDOCODE BEGIN>
func (s *server) handlePostUpdateMetric(w http.ResponseWriter, r *http.Request)
....
<PSEUDOCODE END>
```

далее все хендлеры предлагаю вынести в отдельный(отдельные) файлы
```
health.go
getmetric.go
createmetirc.go
```

следующим шагом предлагаю удалить
```
<PSEUDOCODE BEGIN>
        if metricType != "gauge" && metricType != "counter" {
            http.Error(w, "Не поддерживаемый тип метрики", http.StatusNotImplemented)
            return
        }
<PSEUDOCODE END>
```
у нас в любом случае есть switch

соответственно привести switch к виду
```
        switch metricType {
        case storage.MetricTypeGauge:
            if err := storage.SetGauge(metricName, metricValue); err != nil {
                http.Error(w, fmt.Sprintf("cannot update %q: %s", metricsName, err), http.StatusInternalServerError)
                return
            }

        case "counter":
            ......
        default:
            http.Error(w, "unsupported metric type", http.StatusInternalServerError)
            return
        }

        w.Header().Set("Content-Type", "text/plain")
        w.WriteHeader(http.StatusOK)
```

в handleGetMetric мы сначала запрашиваем метрику, и только потом проверяем тип
предлагаю переделать по стилю handlePostUpdateMetric

2023-04-18 14:59 UTC, juri-breslauer commented on cmd/agent/main.go
> +	}
Добавил изменения

2023-04-19 22:27 UTC, MakeItBright commented on cmd/server/main.go
> +	}
Обновил кодовую базу

2023-04-19 22:29 UTC, MakeItBright commented on cmd/agent/main.go
> +	}
Переделал monitor

2023-04-20 11:08 UTC, mshogin requested changes
Супер! Хорошо доработанная кодовая база. Мы находимся на финишной прямой, осталось несколько небольших, но очень! важных моментов. Предлагаю довести до конца
Полное ревью: https://disk.yandex.ru/i/SPPjq9xHh5IU2Q
Обзор начинается с минуты 37:50
Отправлено на доработку.

2023-04-20 22:27 UTC, MakeItBright commented on cmd/server/main.go
> +	}
Обновил агента
Обновил сервер
Добавил обработку ошибок

2023-04-20 23:22 UTC, mshogin approved these changes
Отлично! Здорово поработали. Спасибо за проделанную работу. Принято.

2023-04-22 07:35 UTC, merged